# Generated by Django 3.2.5 on 2021-07-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='PhotoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('tag', models.ManyToManyField(related_name='photo', to='app.Tag')),
            ],
            options={
                'db_table': 'PhotoImage',
            },
        ),
    ]
